# Birds CUB dataset
birds_images_path: "birds/CUB_200_2011/images"
birds_embedding_path: "birds/cub_icml/"
birds_text_path: "birds/text_c10/"

birds_dataset_path: "birds/birds_10.hdf5"
birds_dataset_path_full: "birds/birds.hdf5"

birds_val_split_path: "birds/valclasses.txt"
birds_train_split_path: "birds/trainclasses.txt"
birds_test_split_path: "birds/testclasses.txt"

birds_coreset_path: "birds/birds_10.txt"

# flowers dataset
flowers_images_path: "flowers"
flowers_embedding_path: "flowers/flowers_icml/"
flowers_text_path: "flowers/text_c10/"

flowers_dataset_path: "flowers/flowers_r10.hdf5"
flowers_dataset_path_full: "flowers/flowers.hdf5"

flowers_val_split_path: "flowers/valclasses.txt"
flowers_train_split_path: "flowers/trainclasses.txt"
flowers_test_split_path: "flowers/testclasses.txt"

flowers_coreset_path: "flowers/flowers_r10.txt"
